version: '3'
services:
  api-gateway:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/api-gateway:dev
    restart: on-failure
    environment:
      - VIRTUAL_HOST=api-gateway.app.com
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/app/src
      - ./libs:/app/libs
      - C:/Mani/logfile:/app/logs
      - C:/Mani/NodeJs-App-Microservices-master/assets:/app/assets  
    depends_on:
      - admin-iam-service
      - admin-users-service
      - buyer-iam-service
      - seller-iam-service

