version: '3.3'
services:
  api-gateway:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/api-gateway:dev
    restart: on-failure
    environment:
      - VIRTUAL_HOST=api-gateway.app.com
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:C:/app/src
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs 
    depends_on:
      # - admin-iam-service
      # - admin-users-service
      # - admin-product-catalog-service
      # - admin-order-quote-service
      # - admin-payment-finance-service
      # - admin-inventory-service
      # - admin-notification-service
      # - admin-subscription-service
      # - admin-reporting-service
      # - admin-request-offer-service
      - admin-master-data-service
      # - admin-integration-service
      # - admin-cms-service

