version: '3.3'

services:

  admin-iam-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-iam-service:dev
    restart: on-failure
    environment: &admin-env
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: eparts_development
      volumes: &admin-volumes
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs

  admin-users-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-users-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes

  admin-product-catalog-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-product-catalog-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes

  admin-order-quote-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-order-quote-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes

  admin-payment-finance-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-payment-finance-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes

  admin-inventory-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-inventory-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes

  admin-notification-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-notification-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes

  admin-subscription-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-subscription-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes

  admin-reporting-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-reporting-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes

  admin-request-offer-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-request-offer-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes

  admin-master-data-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-master-data-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes

  admin-integration-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-integration-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes

  admin-cms-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-cms-service:dev
    restart: on-failure
    environment: *admin-env
    volumes: *admin-volumes