version: "3.3"

services:

  admin-iam-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-iam-service:dev
    restart: on-failure
    environment: &admin-env
      DB_HOST: 10.33.30.5          
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ExZ3naPw@32!perts
      DB_NAME: eparts_core
      COTE_DISCOVERY_REDIS_HOST: 10.33.30.5
      COTE_DISCOVERY_REDIS_PORT: 6379
    volumes:
      - ./microservices/admin/iam-service:C:/app/src
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs
     
  admin-users-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-users-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./microservices/admin/users-service:C:/app/src
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs
   
  admin-product-catalog-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-product-catalog-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./microservices/admin/product-catalog-service:C:/app/src
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs

  admin-order-quote-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-order-quote-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./microservices/admin/order-quote-service:C:/app/src
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs

  admin-payment-finance-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-payment-finance-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./microservices/admin/payment-finance-service:C:/app/src
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs

  admin-inventory-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-inventory-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs
      - ./microservices/admin/inventory-service:C:/app/src

  admin-notification-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-notification-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs
      - ./microservices/admin/notification-service:C:/app/src

  admin-subscription-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-subscription-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs
      - ./microservices/admin/subscription-service:C:/app/src

  admin-reporting-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-reporting-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs
      - ./microservices/admin/reporting-service:C:/app/src

  admin-request-offer-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-request-offer-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./microservices/admin/request-offer-service:C:/app/src
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs

  admin-master-data-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-master-data-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./microservices/admin/master-data-service:C:/app/src
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs

  admin-integration-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-integration-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./microservices/admin/integration-service:C:/app/src
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs
      
  admin-cms-service:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/admin-cms-service:dev
    restart: on-failure
    environment: *admin-env
    volumes:
      - ./libs:C:/app/libs
      - ./assets:C:/app/assets
      - ./logs:C:/app/logs
      - ./microservices/admin/cms-service:C:/app/src